### PR TITLE
Feature/graceful fallback

### PR DESCRIPTION
**Pull request by dingo-d**
Add graceful fallback and small translation fixes.

### CODE REVIEW

**Comment by dingo-d** [comment]
This is a PR for #62 issue.
@grappler can you check if this is working?

**Comment by grappler** [comment]
I would have gone with something more like this https://github.com/nico-martin/AdvancedWPLink/blob/master/advanced-wplink.php#L12

It is first time I have seen `PHP_MAJOR_VERSION` being used.

Could you create a separate PR for the changes in `inc/helpers.php`

**Comment by dingo-d** [comment]
I've fixed the issues and added a separate PR for translations. Should be ok now

**Comment by ernilambar** [comment]
@dingo-d can you please refresh this PR? Since rename PR is merge, there is merge conflict in this PR.

**Comment by dingo-d** [comment]
Hi! I updated the PR, had to recommit since I have spaces set as a default instead of tabs (we use spaces on work :D)

**Comment by dingo-d** [comment]
@grappler Can you check this and merge it? I need to delete my fork, I messed something up while fetching from the upstream, and have extra commits...

**Comment by grappler** [comment]
I tested this on a PHP 5.2 install and it did not work. I was able to set up a PHP 5.2 install with Local by Flywheel.

@dingo-d You can correct your commits locally and then push it to GitHub with `git push --force`

**Comment by dingo-d** [comment]
I will try to test this, will probably try to set up Docker with php 5.2 on it. I was unsuccessful with setting up php 5.2 on VVV.

**Comment by dingo-d** [comment]
I changed the code and tested on local and I got a notification on the top (running php 5.2.4)

screen shot 2017-07-06 at 21 01 41

After 4 days of trying to get php 5.2 working on docker and vvv, I gave up and installed Local by Flywheel :joy:

**Comment by grappler** [comment]
What about "Theme Sniffer requires PHP 5.3 or greater to function."?

Why do we need to add a font style?

Thank you for the screenshot. Do we really want text that says that the plugin could not be activated because of a fatal error. Could we provide more information on how to update?

**Comment by dingo-d** [comment]
If I remove the fonts the notice looks like this

screen shot 2017-07-07 at 08 43 55

As for the fatal error text, that is default from the WordPress, from what I can see you cannot modify that text using a filter or such. Any suggestions?

**Comment by dingo-d** [comment]
And if I use `wp_die` I'll get

screen shot 2017-07-07 at 09 45 54

**Comment by dingo-d** [comment]
Ok, I'm almost there. The last commit did this

screen shot 2017-07-07 at 10 32 02

The thing is, I'm not sure why does the plugin activated message appears. I tried adding the deactivation earlier, but I'm getting an error about `deactivate_plugins()` not exisiting.

**Comment by dingo-d** [comment]
Ok, I removed the plugin notice, but the `Theme Sniffer Page` is still showing.

**Comment by ernilambar** [comment]
@dingo-d May be this will work.
`remove_filter( 'plugin_action_links_' . $plugin, 'theme_sniffer_plugin_settings_link' );`

**Comment by dingo-d** [comment]
@ernilambar That did the trick!

PR can be merged.

**Comment by grappler** [comment]
Thank you for working on this. It works great. Could you squash all of the commits together so that we have a cleaner history? Happy to help to get that to work.

**Comment by dingo-d** [comment]
You mean rebasing? Any help is appreciated :)

**Comment by grappler** [comment]
@dingo-d Ping me on slack and we can go through it.

**Comment by dingo-d** [comment]
I'll open a new PR, my commit history looks like a mess atm

**Pull request closed without merging**
