### PR TITLE
Feature: Enable Cross env fix & Windows tips and tricks

### PR DESCRIPTION
**Pull request by vyskoczilova**

### CODE REVIEW

**Comment by dingo-d** [comment]
I'll try to test this when I get home from WCEU on my PC machine just to be safe, but I haven't forgot about this 😄

**Comment by vyskoczilova** [comment]
@dingo-d Sure :) I'm as well still traveling.

**Comment by dingo-d** [comment]
Tested on my windows machine and it seems to be working 🙂 I had to install node, php and composer to it so that was a fun experience XD

**Comment by vyskoczilova** [comment]
@dingo-d Great :) When'll have spare time, I'll check the other issues too and help you out with this plugin.

**Pull request merged**
