### PR TITLE
Development

### PR DESCRIPTION
**Pull request by dingo-d**
This is the production release PR.

We would like to release the plugin to the wp.org repo so we need to do a final check if everything works, if the readme is correct, etc.

Once this is done, a master branch will be tagged and released and I can submit the plugin in the repo.

## How to test

Clone the repo in your plugins folder and switch to the `development` branch

```bash
git clone git@github.com:WPTRT/theme-sniffer.git && git checkout development
```

After that run

```bash
cd theme-sniffer && composer install && npm install && npm run build
```

This should make the plugin operational (plus create a zip file for production but that's not important as it won't be bundled in the final release).

@ernilambar @grappler If you can review the code, and if all is ok approve it that would be great 🙂

@timelsass Since you've made some great contributions it would be great if you could do a sanity check.

@pattonwebz @kafleg @joyously @jocastaneda @justintadlock  You can also give it a go and report issues if found.

⚠️Notice: Can anybody who is admin check what I messed with travis, since I no longer trigger the travis checks 😕

### CODE REVIEW

**Comment by timelsass** [comment]
@dingo-d did a fresh install and ran build, everything tests out fine so far.  One thing I noticed with multiple themes named the same in the dropdown - the calls for version and which is the active theme are I guess pulled from wp_get_theme - so they all remain the same.  I looked at Theme Check, and it looks like it was resolved by naming duplicates as Theme Name/folder-name.  I don't think that's a blocker though.

**Comment by dingo-d** [comment]
Not a blocker but a good catch, you can open an issue so that we don't forget anything 🙂

**Comment by joyously** [comment]
Plugins in the WP repo are supposed to be production versions. How do I determine if this is the case, given your test instructions to build something? Surely all of this isn't destined for the plugin?

**Comment by timelsass** [comment]
@joyously had said:
> Plugins in the WP repo are supposed to be production versions. How do I determine if this is the case, given your test instructions to build something? Surely all of this isn't destined for the plugin?

The wp.org version would be the build artifact - the .zip file that is generated as a result of doing the build.

**Comment by pattonwebz** [comment]
If you need the production zip file it ends up with:

[theme-sniffer.zip](https://github.com/WPTRT/theme-sniffer/files/2927549/theme-sniffer.zip)

It ends up being around 2.2MB compressed.

**Pull request merged**
