### PR TITLE
Feature/show codes

### LINKED ISSUE #156: Provide rule info for warnings/errors
I think a good feature to add would be when there are warnings/errors we could have some sort of indication as to what rule was actually causing the warning/error.  The main reason is it's hard to reference the actual PHPCS rules while fixing issues and marking the ones that are deemed safe with the correct annotations.

### PR DESCRIPTION
**Pull request by timelsass**
fixes #156

This PR adds the PHPCS codes and a copy to clipboard functionality for annotations to the report (not raw).

image

To test:
1. Run report on twentyninteen.
2. Ensure error/warning sources are displayed.
3. Tool tip should be displayed on hover "Copy Annotation"
4. Click on item.

The result is that the tooltip should change to say "Copied!" and the annotation is copied to your clipboard, so you can press ctrl+v to easily paste it in code.

Notes:  
- The copy to clipboard functionality is the same lib used in Gutenberg.
- Since there was more discussion in #156 about the manually added items by Theme Sniffer, there's some refactoring to be done to generate error/warning source codes for those items.  I think this would be better suited for a new ticket and leave the scope down to just this feature.  For the time being, items without error/warning source codes do not display this feature/row.

### CODE REVIEW

**Comment by dingo-d** [comment]
I have only one minor issue with this - could the copy code be extracted to a separate class? I can work on this if you want 🙂

**Comment by timelsass** [comment]
Yeah, I was going to get there, but didn't lol  - I hadn't really looked much into this area, but was thinking using either react or an underscore template might be a bit easier to work with in the future instead of cloning the empty divs too.

**Comment by dingo-d** [comment]
Can you fix the conflicts and then we can merge this. 

Once we get all the major functionality in, I'd like to work more on tests so that we can refactor the plugin properly. As currently I see some issues with classes maybe being too big and violating the SRP.

**Comment by dingo-d** [comment]
HI @timelsass can you just fix the conflicts so that we can merge this? I'd like to continue the work on the theme sniffer 🙂 

If you don't have the time, I can pull your branch and create a new PR with these changes (your commits should be visible).

**Pull request merged**
