### PR TITLE
Update download link in README

### PR DESCRIPTION
**Pull request by ryanhalliday-arlo**

### CODE REVIEW

**Comment by pattonwebz** [comment]
LGTM :+1:

**Comment by dingo-d** [comment]
Hi @ryanhalliday-arlo! Thanks for the contribution 🙂 

This looks good, but can you just change the base branch to `development` instead of `master`?

**Comment by ryanhalliday-arlo** [comment]
@dingo-d Yep sorry - all done!

**Comment by timelsass** [comment]
I think now we should update to point to wordpress.org latest: https://downloads.wordpress.org/plugin/theme-sniffer.latest-stable.zip

or if continue to use github releases version we could use: https://github.com/WPTRT/theme-sniffer/releases/latest/download/theme-sniffer.zip  

This way we don't have to continuously update the readme :smile:

**Comment by dingo-d** [comment]
@timelsass I'll merge this and then we can create a new PR in which we'll further update the Readme 🙂

**Pull request merged**
